//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AxFExtractor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AxFExtractor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to %YAML 1.1
        ///%TAG !u! tag:unity3d.com,2011:
        ///--- !u!21 &amp;2100000
        ///Material:
        ///  serializedVersion: 6
        ///  m_ObjectHideFlags: 0
        ///  m_CorrespondingSourceObject: {fileID: 0}
        ///  m_PrefabInternal: {fileID: 0}
        ///  m_Name: Material
        ///  m_Shader: {fileID: 4800000, guid: 6510c57cccce5674092bdc0dd1ae98c1, type: 3}
        ///  m_ShaderKeywords: _AXF_BRDF_TYPE_SVBRDF
        ///  m_LightmapFlags: 4
        ///  m_EnableInstancingVariants: 0
        ///  m_DoubleSidedGI: 0
        ///  m_CustomRenderQueue: 2000
        ///  stringTagMap: {}
        ///  disabledShaderPasses: []
        ///  m_SavedProperties:
        ///    serializ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TemplateMaterial {
            get {
                return ResourceManager.GetString("TemplateMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fileFormatVersion: 2
        ///guid: &lt;GUID&gt;
        ///TextureImporter:
        ///  fileIDToRecycleName: {}
        ///  externalObjects: {}
        ///  serializedVersion: 6
        ///  mipmaps:
        ///    mipMapMode: 0
        ///    enableMipMap: 1
        ///    sRGBTexture: &lt;sRGB&gt;
        ///    linearTexture: 0
        ///    fadeOut: 0
        ///    borderMipMap: 0
        ///    mipMapsPreserveCoverage: 0
        ///    alphaTestReferenceValue: 0.5
        ///    mipMapFadeDistanceStart: 1
        ///    mipMapFadeDistanceEnd: 3
        ///  bumpmap:
        ///    convertToNormalMap: 0
        ///    externalNormalMap: 0
        ///    heightScale: 0.25
        ///    normalMapFilter: 0
        ///  isReadable: 0
        ///  streamingMip [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string TemplateMeta {
            get {
                return ResourceManager.GetString("TemplateMeta", resourceCulture);
            }
        }
    }
}
