//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SharpMath.FFT.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SharpMath.FFT.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        ///// Common FFT code
        ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        /////
        ///
        ///cbuffer : register(b0) {
        ///	float	_sign;
        /////	uint	_groupSize;
        ///};
        ///
        ///
        ///uint	wang_hash(uint seed) {
        ///    seed = (seed ^ 61) ^ (seed &gt;&gt; 16);
        ///    seed *= 9;
        ///    seed = seed ^ (seed &gt;&gt; 4);
        ///    seed *= 0x27d4eb2d;
        ///    seed = seed ^ (seed &gt;&gt; 15) [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FFT {
            get {
                return ResourceManager.GetString("FFT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        ///// 1D FFT
        ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
        /////
        ///#include &quot;FFT.hlsl&quot;
        ///
        ///Texture2D&lt;float2&gt;	_texIn : register(t0);
        ///RWTexture2D&lt;float2&gt;	_texOut : register(u0);
        ///
        ///// Applies FFT from stage 0 (size 1) to stage 6 (size 64)
        ///// NOTE: Each thread reads and writes 2 values so each thread at stage 0 reads 2 s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FFT1D {
            get {
                return ResourceManager.GetString("FFT1D", resourceCulture);
            }
        }
    }
}
