//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZetaHtmlEditControl.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ZetaHtmlEditControl.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string HtmlEditControl_ExecuteSystemInfo_Information {
            get {
                return ResourceManager.GetString("HtmlEditControl_ExecuteSystemInfo_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected path &apos;{0}&apos;..
        /// </summary>
        internal static string MyModule_Process_Unexpected_path___0___ {
            get {
                return ResourceManager.GetString("MyModule_Process_Unexpected_path___0___", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A value for the HtmlTemplate must be provided..
        /// </summary>
        internal static string SR_HtmlEditControl_HtmlTemplate_AvaluefortheHtmlTemplatemustbeprovided {
            get {
                return ResourceManager.GetString("SR_HtmlEditControl_HtmlTemplate_AvaluefortheHtmlTemplatemustbeprovided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing &apos;##BODY##&apos; inside the HtmlTemplate property value..
        /// </summary>
        internal static string SR_HtmlEditControl_HtmlTemplate_MissingBODYinsidetheHtmlTemplatepropertyvalue {
            get {
                return ResourceManager.GetString("SR_HtmlEditControl_HtmlTemplate_MissingBODYinsidetheHtmlTemplatepropertyvalue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        internal static string Str_HorizontalAlignmentType_Center {
            get {
                return ResourceManager.GetString("Str_HorizontalAlignmentType_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justify.
        /// </summary>
        internal static string Str_HorizontalAlignmentType_Justify {
            get {
                return ResourceManager.GetString("Str_HorizontalAlignmentType_Justify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string Str_HorizontalAlignmentType_Left {
            get {
                return ResourceManager.GetString("Str_HorizontalAlignmentType_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple.
        /// </summary>
        internal static string Str_HorizontalAlignmentType_Multiple {
            get {
                return ResourceManager.GetString("Str_HorizontalAlignmentType_Multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string Str_HorizontalAlignmentType_Right {
            get {
                return ResourceManager.GetString("Str_HorizontalAlignmentType_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string Str_HorizontalAlignmentType_Standard {
            get {
                return ResourceManager.GetString("Str_HorizontalAlignmentType_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell properties.
        /// </summary>
        internal static string Str_UIHtml_CellProperties {
            get {
                return ResourceManager.GetString("Str_UIHtml_CellProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column properties.
        /// </summary>
        internal static string Str_UIHtml_ColumnProperties {
            get {
                return ResourceManager.GetString("Str_UIHtml_ColumnProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arial.
        /// </summary>
        internal static string Str_UIHtml_HtmlFontFamilyArial {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontFamilyArial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Courier new.
        /// </summary>
        internal static string Str_UIHtml_HtmlFontFamilyCourierNew {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontFamilyCourierNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Garamond.
        /// </summary>
        internal static string Str_UIHtml_HtmlFontFamilyGaramond {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontFamilyGaramond", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Georgia.
        /// </summary>
        internal static string Str_UIHtml_HtmlFontFamilyGeorgia {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontFamilyGeorgia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string Str_UIHtml_HtmlFontFamilyStandard {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontFamilyStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Times.
        /// </summary>
        internal static string Str_UIHtml_HtmlFontFamilyTimes {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontFamilyTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verdana.
        /// </summary>
        internal static string Str_UIHtml_HtmlFontFamilyVerdana {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontFamilyVerdana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        internal static string Str_UIHtml_HtmlFontSize1 {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontSize1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Str_UIHtml_HtmlFontSize2 {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontSize2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string Str_UIHtml_HtmlFontSize3 {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontSize3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string Str_UIHtml_HtmlFontSize4 {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontSize4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string Str_UIHtml_HtmlFontSize5 {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontSize5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string Str_UIHtml_HtmlFontSize6 {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontSize6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string Str_UIHtml_HtmlFontSize7 {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontSize7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string Str_UIHtml_HtmlFontSizeStandard {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlFontSizeStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address &lt;address&gt;.
        /// </summary>
        internal static string Str_UIHtml_HtmlStyleAddress {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlStyleAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formatted &lt;pre&gt;.
        /// </summary>
        internal static string Str_UIHtml_HtmlStyleFormatted {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlStyleFormatted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading 1 &lt;h1&gt;.
        /// </summary>
        internal static string Str_UIHtml_HtmlStyleHeading1 {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlStyleHeading1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading 2 &lt;h2&gt;.
        /// </summary>
        internal static string Str_UIHtml_HtmlStyleHeading2 {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlStyleHeading2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heading 3 &lt;h3&gt;.
        /// </summary>
        internal static string Str_UIHtml_HtmlStyleHeading3 {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlStyleHeading3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string Str_UIHtml_HtmlStyleNormal {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlStyleNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragraph &lt;p&gt;.
        /// </summary>
        internal static string Str_UIHtml_HtmlStyleParagraph {
            get {
                return ResourceManager.GetString("Str_UIHtml_HtmlStyleParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AbsBottom.
        /// </summary>
        internal static string Str_UIHtml_ImageAlignAbsBottom {
            get {
                return ResourceManager.GetString("Str_UIHtml_ImageAlignAbsBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AbsMiddle.
        /// </summary>
        internal static string Str_UIHtml_ImageAlignAbsMiddle {
            get {
                return ResourceManager.GetString("Str_UIHtml_ImageAlignAbsMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base line.
        /// </summary>
        internal static string Str_UIHtml_ImageAlignBaseLine {
            get {
                return ResourceManager.GetString("Str_UIHtml_ImageAlignBaseLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        internal static string Str_UIHtml_ImageAlignBottom {
            get {
                return ResourceManager.GetString("Str_UIHtml_ImageAlignBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string Str_UIHtml_ImageAlignLeft {
            get {
                return ResourceManager.GetString("Str_UIHtml_ImageAlignLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle.
        /// </summary>
        internal static string Str_UIHtml_ImageAlignMiddle {
            get {
                return ResourceManager.GetString("Str_UIHtml_ImageAlignMiddle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string Str_UIHtml_ImageAlignRight {
            get {
                return ResourceManager.GetString("Str_UIHtml_ImageAlignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string Str_UIHtml_ImageAlignStandard {
            get {
                return ResourceManager.GetString("Str_UIHtml_ImageAlignStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text top.
        /// </summary>
        internal static string Str_UIHtml_ImageAlignTextTop {
            get {
                return ResourceManager.GetString("Str_UIHtml_ImageAlignTextTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        internal static string Str_UIHtml_ImageAlignTop {
            get {
                return ResourceManager.GetString("Str_UIHtml_ImageAlignTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row properties.
        /// </summary>
        internal static string Str_UIHtml_RowProperties {
            get {
                return ResourceManager.GetString("Str_UIHtml_RowProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table properties.
        /// </summary>
        internal static string Str_UIHtml_TableProperties {
            get {
                return ResourceManager.GetString("Str_UIHtml_TableProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base line.
        /// </summary>
        internal static string Str_VerticalAlignmentType_BaseLine {
            get {
                return ResourceManager.GetString("Str_VerticalAlignmentType_BaseLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        internal static string Str_VerticalAlignmentType_Bottom {
            get {
                return ResourceManager.GetString("Str_VerticalAlignmentType_Bottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Middle.
        /// </summary>
        internal static string Str_VerticalAlignmentType_Middle {
            get {
                return ResourceManager.GetString("Str_VerticalAlignmentType_Middle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiple.
        /// </summary>
        internal static string Str_VerticalAlignmentType_Multiple {
            get {
                return ResourceManager.GetString("Str_VerticalAlignmentType_Multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        internal static string Str_VerticalAlignmentType_Standard {
            get {
                return ResourceManager.GetString("Str_VerticalAlignmentType_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        internal static string Str_VerticalAlignmentType_Top {
            get {
                return ResourceManager.GetString("Str_VerticalAlignmentType_Top", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to acquire free port..
        /// </summary>
        internal static string WebServer_getFreePort_Unable_to_acquire_free_port_ {
            get {
                return ResourceManager.GetString("WebServer_getFreePort_Unable_to_acquire_free_port_", resourceCulture);
            }
        }
    }
}
