#pragma once
#include "PixelFormats.h"

PixelFormatR8::Desc				PixelFormatR8::DESCRIPTOR;
PixelFormatRGBA8::Desc			PixelFormatRGBA8::DESCRIPTOR;
PixelFormatRGBA8_sRGB::Desc		PixelFormatRGBA8_sRGB::DESCRIPTOR;
PixelFormatR16F::Desc			PixelFormatR16F::DESCRIPTOR;
PixelFormatR16_UNORM::Desc		PixelFormatR16_UNORM::DESCRIPTOR;
PixelFormatRG16F::Desc			PixelFormatRG16F::DESCRIPTOR;
PixelFormatRG16_UNORM::Desc		PixelFormatRG16_UNORM::DESCRIPTOR;
PixelFormatRGBA16_UINT::Desc	PixelFormatRGBA16_UINT::DESCRIPTOR;
PixelFormatRGBA16_UNORM::Desc	PixelFormatRGBA16_UNORM::DESCRIPTOR;
PixelFormatRGBA16F::Desc		PixelFormatRGBA16F::DESCRIPTOR;
PixelFormatR32F::Desc			PixelFormatR32F::DESCRIPTOR;
PixelFormatR32_UINT::Desc		PixelFormatR32_UINT::DESCRIPTOR;
PixelFormatRG32F::Desc			PixelFormatRG32F::DESCRIPTOR;
PixelFormatRGBA32F::Desc		PixelFormatRGBA32F::DESCRIPTOR;
PixelFormatBC3_UNORM::Desc		PixelFormatBC3_UNORM::DESCRIPTOR;
PixelFormatBC3_UNORM_sRGB::Desc	PixelFormatBC3_UNORM_sRGB::DESCRIPTOR;
