//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MaterialsOptimizer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MaterialsOptimizer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entity {
        ///	entityDef probe {
        ///		inherit = &quot;blacksparrow/probe&quot;;
        ///		editorVars {
        ///			placeable = true;
        ///			editorName = &quot;&quot;;
        ///		}
        ///		edit = {
        ///			spawnPosition = {
        ///				x = -0.0189583302;
        ///				y = -1.7630009651;
        ///				z = 0.3187797666;
        ///			}
        ///			m_usedForIBL = true;
        ///			m_probe = &quot;&lt;MAP_PATH&gt;/probe&quot;;
        ///		}
        ///	}
        ///}
        ///.
        /// </summary>
        internal static string entityTemplateProbe {
            get {
                return ResourceManager.GetString("entityTemplateProbe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to entity {
        ///	entityDef &lt;ENTITY_NAME&gt; {
        ///		inherit = &quot;func/static&quot;;
        ///		editorVars {
        ///			placeable = true;
        ///		}
        ///		edit = {
        ///			spawnPosition = {
        ///				&lt;POSITION&gt;
        ///			}
        ///			renderModelInfo = ! {
        ///				model = &quot;models/templates/cube_1meter.lwo&quot;;
        ///				m_probeRenderModeNeedToBeConverted = false;
        ///				m_customMaterials = {
        ///					num = 1;
        ///					item[0] = &quot;&lt;MATERIAL_NAME&gt;&quot;;
        ///				}
        ///				scale = {
        ///					x = 0.9499999881;
        ///					y = 0.1000000015;
        ///					z = 0.9499999881;
        ///				}
        ///			}
        ///			m_collisionSettings = {
        ///				m_version = 20150324;
        ///			}
        ///		}
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string entityTemplateSlate {
            get {
                return ResourceManager.GetString("entityTemplateSlate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version 6
        ///entity {
        ///	entityDef world {
        ///		inherit = &quot;worldspawn&quot;;
        ///		editorVars {
        ///			placeable = true;
        ///		}
        ///		edit = {
        ///			m_worldEnvironment = &quot;env/generic/exterior_daylight&quot;;
        ///		}
        ///	}
        ///}
        ///.
        /// </summary>
        internal static string mapHeader {
            get {
                return ResourceManager.GetString("mapHeader", resourceCulture);
            }
        }
    }
}
